/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StockEntryRouteImport } from './routes/stock-entry'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminStockSummaryRouteImport } from './routes/admin.stock-summary'
import { Route as AdminShiftsRouteImport } from './routes/admin.shifts'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfitCalculatorRouteImport } from './routes/admin.profit-calculator'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminLowStockRouteImport } from './routes/admin.low-stock'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDailyExpensesRouteImport } from './routes/admin.daily-expenses'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCashierReportRouteImport } from './routes/admin.cashier-report'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockEntryRoute = StockEntryRouteImport.update({
  id: '/stock-entry',
  path: '/stock-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockSummaryRoute = AdminStockSummaryRouteImport.update({
  id: '/stock-summary',
  path: '/stock-summary',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShiftsRoute = AdminShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfitCalculatorRoute = AdminProfitCalculatorRouteImport.update({
  id: '/profit-calculator',
  path: '/profit-calculator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLowStockRoute = AdminLowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyExpensesRoute = AdminDailyExpensesRouteImport.update({
  id: '/daily-expenses',
  path: '/daily-expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCashierReportRoute = AdminCashierReportRouteImport.update({
  id: '/cashier-report',
  path: '/cashier-report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/returns': typeof ReturnsRoute
  '/stock-entry': typeof StockEntryRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/cashier-report': typeof AdminCashierReportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/daily-expenses': typeof AdminDailyExpensesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/low-stock': typeof AdminLowStockRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profit-calculator': typeof AdminProfitCalculatorRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/stock-summary': typeof AdminStockSummaryRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/returns': typeof ReturnsRoute
  '/stock-entry': typeof StockEntryRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/cashier-report': typeof AdminCashierReportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/daily-expenses': typeof AdminDailyExpensesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/low-stock': typeof AdminLowStockRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profit-calculator': typeof AdminProfitCalculatorRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/stock-summary': typeof AdminStockSummaryRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/returns': typeof ReturnsRoute
  '/stock-entry': typeof StockEntryRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/cashier-report': typeof AdminCashierReportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/daily-expenses': typeof AdminDailyExpensesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/low-stock': typeof AdminLowStockRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profit-calculator': typeof AdminProfitCalculatorRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/stock-summary': typeof AdminStockSummaryRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/pos'
    | '/returns'
    | '/stock-entry'
    | '/suppliers'
    | '/admin/backup'
    | '/admin/cashier-report'
    | '/admin/categories'
    | '/admin/daily-expenses'
    | '/admin/dashboard'
    | '/admin/low-stock'
    | '/admin/products'
    | '/admin/profit-calculator'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/stock-summary'
    | '/admin/suppliers'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/pos'
    | '/returns'
    | '/stock-entry'
    | '/suppliers'
    | '/admin/backup'
    | '/admin/cashier-report'
    | '/admin/categories'
    | '/admin/daily-expenses'
    | '/admin/dashboard'
    | '/admin/low-stock'
    | '/admin/products'
    | '/admin/profit-calculator'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/stock-summary'
    | '/admin/suppliers'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/pos'
    | '/returns'
    | '/stock-entry'
    | '/suppliers'
    | '/admin/backup'
    | '/admin/cashier-report'
    | '/admin/categories'
    | '/admin/daily-expenses'
    | '/admin/dashboard'
    | '/admin/low-stock'
    | '/admin/products'
    | '/admin/profit-calculator'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/stock-summary'
    | '/admin/suppliers'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  ReturnsRoute: typeof ReturnsRoute
  StockEntryRoute: typeof StockEntryRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-entry': {
      id: '/stock-entry'
      path: '/stock-entry'
      fullPath: '/stock-entry'
      preLoaderRoute: typeof StockEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock-summary': {
      id: '/admin/stock-summary'
      path: '/stock-summary'
      fullPath: '/admin/stock-summary'
      preLoaderRoute: typeof AdminStockSummaryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shifts': {
      id: '/admin/shifts'
      path: '/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AdminShiftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profit-calculator': {
      id: '/admin/profit-calculator'
      path: '/profit-calculator'
      fullPath: '/admin/profit-calculator'
      preLoaderRoute: typeof AdminProfitCalculatorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/low-stock': {
      id: '/admin/low-stock'
      path: '/low-stock'
      fullPath: '/admin/low-stock'
      preLoaderRoute: typeof AdminLowStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily-expenses': {
      id: '/admin/daily-expenses'
      path: '/daily-expenses'
      fullPath: '/admin/daily-expenses'
      preLoaderRoute: typeof AdminDailyExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cashier-report': {
      id: '/admin/cashier-report'
      path: '/cashier-report'
      fullPath: '/admin/cashier-report'
      preLoaderRoute: typeof AdminCashierReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBackupRoute: typeof AdminBackupRoute
  AdminCashierReportRoute: typeof AdminCashierReportRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDailyExpensesRoute: typeof AdminDailyExpensesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLowStockRoute: typeof AdminLowStockRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfitCalculatorRoute: typeof AdminProfitCalculatorRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShiftsRoute: typeof AdminShiftsRoute
  AdminStockSummaryRoute: typeof AdminStockSummaryRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBackupRoute: AdminBackupRoute,
  AdminCashierReportRoute: AdminCashierReportRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDailyExpensesRoute: AdminDailyExpensesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLowStockRoute: AdminLowStockRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfitCalculatorRoute: AdminProfitCalculatorRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShiftsRoute: AdminShiftsRoute,
  AdminStockSummaryRoute: AdminStockSummaryRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  ReturnsRoute: ReturnsRoute,
  StockEntryRoute: StockEntryRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
